'use client';

import axios from 'axios';
import React, { createContext, useContext, useState, useEffect } from 'react';

interface User {
  id: string;
  email: string;
  name: string;
}

interface AuthContextType {
  user: User | null;
  isLoading: boolean;
  login: (email: string, password: string) => Promise<void>;
  signup: (email: string, password: string, name: string) => Promise<void>;
  logout: () => void;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export function AuthProvider({ children }: { children: React.ReactNode }) {
  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  // let [reamaining,setRemaining] = useState(3);

  // Load user from localStorage on mount
  useEffect(() => {
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      try {
        setUser(JSON.parse(storedUser));
      } catch (error) {
        console.error('Failed to parse stored user:', error);
        localStorage.removeItem('user');
      }
    }
    setIsLoading(false);
  }, []);


  const refectchUser = async () => {
    setIsLoading(true);

    let res = await axios.get('/api/refetch');

    console.log("Response", res);
    // setUser(res);
  }
  const login = async (email: string, password: string) => {
    setIsLoading(true);

    try {
      // 1. Basic Validation
      if (!email || !password) {
        throw new Error('Email and password required');
      }

      // 2. Real API Call
      // Note: Remove the artificial setTimeout, you don't need it with real APIs
      const res = await axios.post('/api/auth/login', { email, password });

      console.log("Login Success:", res.data);

      // 3. Set User Data on Success
      setUser(res.data);
      localStorage.setItem('user', JSON.stringify(res.data));

    } catch (error: any) {
      // --- 🚨 THIS IS THE FIX 🚨 ---

      // Axios throws an error for 4xx/5xx responses.
      // We need to look inside 'error.response.data' to find your specific message.

      const serverMessage =
        error.response?.data?.message ||  // What your Next.js API sends
        error.response?.data?.error ||    // Alternative key
        error.message ||                  // Fallback (e.g. "Network Error")
        "Login failed";

      console.log("Login Error:", serverMessage);

      // You might want to show this to the user via a toast or alert
      // alert(serverMessage); 

      // Re-throw if you want the calling component to handle the UI alert
      throw new Error(serverMessage);

    } finally {
      // 4. Always turn off loading, even if it failed
      setIsLoading(false);
    }
  };

  const signup = async (email: string, password: string, name: string) => {
    setIsLoading(true);

    try {
      // 1. Basic Client-side Validation
      if (!email || !password || !name) {
        throw new Error('All fields required');
      }

      // 2. Real API Call
      const res = await axios.post('/api/auth/signup', { email, password, name });

      console.log("Response from signup:", res.data);

      // 3. Update State with REAL Backend Data
      // We use 'res.data' because it contains the ID and Token generated by the server.
      // The manually created 'newUser' object would be missing these vital fields.
      setUser(res.data);
      localStorage.setItem('user', JSON.stringify(res.data));

    } catch (error: any) {
      // 4. Error Handling
      // Extract the specific message sent by your backend (e.g., "User already exists")
      const serverMessage =
        error.response?.data?.message ||
        error.response?.data?.error ||
        error.message ||
        "Signup failed";

      console.log("Signup Error:", serverMessage);

      // Re-throw the error so your UI component can show an alert or toast
      throw new Error(serverMessage);

    } finally {
      // 5. Cleanup
      // This runs whether the signup succeeds OR fails
      setIsLoading(false);
    }
  };

  const logout = () => {
    setUser(null);
    localStorage.removeItem('user');
  };

  return (
    <AuthContext.Provider value={{ user, isLoading, login, signup, logout, refectchUser,setUser }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within AuthProvider');
  }
  return context;
}
